INSERT INTO countries (country) values ('Австралія');
INSERT INTO countries (country) values ('Австрія');
INSERT INTO countries (country) values ('Азербайджан');
INSERT INTO countries (country) values ('Албанія');
INSERT INTO countries (country) values ('Андорра');
INSERT INTO countries (country) values ('Аргентина');
INSERT INTO countries (country) values ('Багами');
INSERT INTO countries (country) values ('Барбадос');
INSERT INTO countries (country) values ('Бахрейн');
INSERT INTO countries (country) values ('Беліз');
INSERT INTO countries (country) values ('Бельгія');
INSERT INTO countries (country) values ('Білорусь');
INSERT INTO countries (country) values ('Болгарія');
INSERT INTO countries (country) values ('Болівія');
INSERT INTO countries (country) values ('Боснія і Герцеговина');
INSERT INTO countries (country) values ('Ботсвана');
INSERT INTO countries (country) values ('Бразилія');
INSERT INTO countries (country) values ('Бруней');
INSERT INTO countries (country) values ('Бурунді');
INSERT INTO countries (country) values ('Вануату');
INSERT INTO countries (country) values ('Венесуела');
INSERT INTO countries (country) values ('Великобританія');
INSERT INTO countries (country) values ('Вірменія');
INSERT INTO countries (country) values ('Гайана');
INSERT INTO countries (country) values ('Гватемала');
INSERT INTO countries (country) values ('Гондурас');
INSERT INTO countries (country) values ('Гренада');
INSERT INTO countries (country) values ('Греція');
INSERT INTO countries (country) values ('Грузія');
INSERT INTO countries (country) values ('Данія');
INSERT INTO countries (country) values ('Домініканська Республіка');
INSERT INTO countries (country) values ('Еквадор');
INSERT INTO countries (country) values ('Естонія');
INSERT INTO countries (country) values ('Ізраїль');
INSERT INTO countries (country) values ('Індія');
INSERT INTO countries (country) values ('Ірландія');
INSERT INTO countries (country) values ('Іспанія');
INSERT INTO countries (country) values ('Італія');
INSERT INTO countries (country) values ('Казахстан');
INSERT INTO countries (country) values ('Киргизстан');
INSERT INTO countries (country) values ('Китай');
INSERT INTO countries (country) values ('Кіпр');
INSERT INTO countries (country) values ('Колумбія');
INSERT INTO countries (country) values ('Нідерланди');
INSERT INTO countries (country) values ('Косово');
INSERT INTO countries (country) values ('Коста-Рика');
INSERT INTO countries (country) values ('Латвія');
INSERT INTO countries (country) values ('Литва');
INSERT INTO countries (country) values ('Ліхтенштейн');
INSERT INTO countries (country) values ('Люксембург');
INSERT INTO countries (country) values ('Маврикій');
INSERT INTO countries (country) values ('Мальта');
INSERT INTO countries (country) values ('Марокко');
INSERT INTO countries (country) values ('Мексика');
INSERT INTO countries (country) values ('Молдова');
INSERT INTO countries (country) values ('Монако');
INSERT INTO countries (country) values ('Монголія');
INSERT INTO countries (country) values ('Намібія');
INSERT INTO countries (country) values ('Нікарагуа');
INSERT INTO countries (country) values ('Німеччина');
INSERT INTO countries (country) values ('Нова Зеландія');
INSERT INTO countries (country) values ('Норвегія');
INSERT INTO countries (country) values ('Оман');
INSERT INTO countries (country) values ('Панама');
INSERT INTO countries (country) values ('Парагвай');
INSERT INTO countries (country) values ('Перу');
INSERT INTO countries (country) values ('ПАР');
INSERT INTO countries (country) values ('Польща');
INSERT INTO countries (country) values ('Португалія');
INSERT INTO countries (country) values ('Республіка Корея');
INSERT INTO countries (country) values ('Росія');
INSERT INTO countries (country) values ('Румунія');
INSERT INTO countries (country) values ('Сан-Марино');
INSERT INTO countries (country) values ('Сербія');
INSERT INTO countries (country) values ('Сінгапур');
INSERT INTO countries (country) values ('Словаччина');
INSERT INTO countries (country) values ('Словенія');
INSERT INTO countries (country) values ('США');
INSERT INTO countries (country) values ('Таджикистан');
INSERT INTO countries (country) values ('Туніс');
INSERT INTO countries (country) values ('Туреччина');
INSERT INTO countries (country) values ('Угорщина');
INSERT INTO countries (country) values ('Узбекистан');
INSERT INTO countries (country) values ('Україна');
INSERT INTO countries (country) values ('Філіппіни');
INSERT INTO countries (country) values ('Фінляндія');
INSERT INTO countries (country) values ('Франція');
INSERT INTO countries (country) values ('Хорватія');
INSERT INTO countries (country) values ('Чехія');
INSERT INTO countries (country) values ('Чорногорія');
INSERT INTO countries (country) values ('Швейцарія');
INSERT INTO countries (country) values ('Швеція');
INSERT INTO countries (country) values ('Японія');

INSERT INTO genres (genre) values ('аніме');
INSERT INTO genres (genre) values ('біографічний');
INSERT INTO genres (genre) values ('бойовик');
INSERT INTO genres (genre) values ('вестерн');
INSERT INTO genres (genre) values ('військовий');
INSERT INTO genres (genre) values ('детектив');
INSERT INTO genres (genre) values ('дитячий');
INSERT INTO genres (genre) values ('документальний');
INSERT INTO genres (genre) values ('драма');
INSERT INTO genres (genre) values ('історичний');
INSERT INTO genres (genre) values ('кінокомікс');
INSERT INTO genres (genre) values ('комедія');
INSERT INTO genres (genre) values ('концерт');
INSERT INTO genres (genre) values ('короткометражний');
INSERT INTO genres (genre) values ('кримінал');
INSERT INTO genres (genre) values ('мелодрама');
INSERT INTO genres (genre) values ('містика');
INSERT INTO genres (genre) values ('музика');
INSERT INTO genres (genre) values ('мультфільм');
INSERT INTO genres (genre) values ('мюзикл');
INSERT INTO genres (genre) values ('науковий');
INSERT INTO genres (genre) values ('нуар');
INSERT INTO genres (genre) values ('пригоди');
INSERT INTO genres (genre) values ('реаліті шоу');
INSERT INTO genres (genre) values ('сімейний');
INSERT INTO genres (genre) values ('спорт');
INSERT INTO genres (genre) values ('ток шоу');
INSERT INTO genres (genre) values ('трилер');
INSERT INTO genres (genre) values ('жахи');
INSERT INTO genres (genre) values ('фантастика');
INSERT INTO genres (genre) values ('фентезі');

INSERT INTO films (name, premiere, directors, screenwriters, actors) values('1 film', '2021-01-01 15:16', '1 director', '1 screenwriter', '1 actor');
INSERT INTO films (name, premiere, directors, screenwriters, actors) values('2 film', '2021-01-01 15:16', '2 director', '2 screenwriter', '2 actor');
INSERT INTO films (name, premiere, directors, screenwriters, actors) values('3 film', '2021-01-01 15:16', '3 director', '3 screenwriter', '3 actor');
INSERT INTO films (name, premiere, directors, screenwriters, actors) values('4 film', '2021-01-01 15:16', '4 director', '4 screenwriter', '4 actor');

INSERT INTO posts (user_id, title, body, created_ts, film_id) values(100, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 07:00', 1);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(100, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 08:00', 2);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(100, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 08:15', 3);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(100, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 09:00', 4);

INSERT INTO posts (user_id, title, body, created_ts, film_id) values(101, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 10:00', 1);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(101, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 11:00', 2);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(101, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 12:00', 3);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(101, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 13:00', 4);

INSERT INTO posts (user_id, title, body, created_ts, film_id) values(102, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 13:23', 1);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(102, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 14:01', 2);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(102, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 14:03', 3);
INSERT INTO posts (user_id, title, body, created_ts, film_id) values(102, 'It`s a title for your post!', 'It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! It`s a body for your post! ', '2022-01-01 15:16', 4);


INSERT INTO categorization (genre_id, film_id) values (1,1);
INSERT INTO categorization (genre_id, film_id) values (2,2);
INSERT INTO categorization (genre_id, film_id) values (1,2);
INSERT INTO categorization (genre_id, film_id) values (2,1);
INSERT INTO categorization (genre_id, film_id) values (3,3);
INSERT INTO categorization (genre_id, film_id) values (4,4);

INSERT INTO producing (country_id, film_id) values (1,1);
INSERT INTO producing (country_id, film_id) values (2,2);
INSERT INTO producing (country_id, film_id) values (1,2);
INSERT INTO producing (country_id, film_id) values (2,1);
INSERT INTO producing (country_id, film_id) values (3,3);
INSERT INTO producing (country_id, film_id) values (4,4);
